version: "3.7"
services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      target: withUser
      args:
        - UESR_NAME=dev
        - USER_ID=1000
        - GROUP_ID=1000
    user: dev
    ports:
      - 127.0.0.1:1313:1313
    volumes:
      - ..:/workspace
    working_dir: /workspace
