version: "3.7"
services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      target: withUser
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    user: node
    volumes:
      - .:/workspace
