#!/usr/bin/env bash
set -euo pipefail

if [ $# -gt 0 ]; then
  sh_files=()
  toml_files=()
  md_files=()
  for file in "$@"; do
    case "$file" in
      *.sh) sh_files+=("$file") ;;
      *.toml) toml_files+=("$file") ;;
      *.md) md_files+=("$file") ;;
    esac
  done
else
  mapfile -t sh_files < <(git ls-files '*.sh')
  mapfile -t toml_files < <(git ls-files '*.toml')
  mapfile -t md_files < <(git ls-files '*.md')
fi

if [ ${#sh_files[@]} -gt 0 ]; then shfmt -w -i 2 -ci -- "${sh_files[@]}"; fi
if [ ${#toml_files[@]} -gt 0 ]; then taplo format "${toml_files[@]}"; fi
if [ ${#md_files[@]} -gt 0 ]; then prettier --write "${md_files[@]}"; fi
