version: "3.4"
services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: sleep infinity
