profile = "litellm-gpt4_1"

[model_providers.litellm]
name = "LiteLLM"
base_url = "http://127.0.0.1:4000/v1"

[profiles.litellm-gpt4_1]
model = "gpt-4.1"
model_provider = "litellm"

[profiles.litellm-claude4sonnet]
model = "claude-4-sonnet"
model_provider = "litellm"

[mcp_servers.serena]
command = "serena"
args = ["start-mcp-server", "--context", "codex"]
