#!/usr/bin/env bash

set -euo pipefail

function GH_WITH_TOKEN() {
  local -a ENV_VARS=()
  if [ "$(uname)" = "Linux" ]; then
    ENV_VARS+=(
      "GH_TOKEN=$(bw get password f790060a-8874-4254-b551-b3c4004fb4b 2>/dev/null)"
    )
  fi
  readonly ENV_VARS

  env "${ENV_VARS[@]}" gh auth git-credential "$@"
}

GH_WITH_TOKEN "$@"
