#!/usr/bin/env bash

set -euo pipefail

function GH_WITH_TOKEN() {
  local -a ENV_VARS=()
  if [ "$(uname)" = "Linux" ]; then
    ENV_VARS+=(
      "GH_TOKEN=$(pass show github/token)"
    )
  fi
  readonly ENV_VARS

  env "${ENV_VARS[@]}" gh auth git-credential "$@"
}

GH_WITH_TOKEN "$@"
