version: "3.7"
services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      target: withUser
      args:
        - USER_NAME=dev
        - USER_ID=1000
        - GROUP_ID=1000
    user: dev
    environment:
      - HOME=/home/dev
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: sleep infinity
