
# tap repositories and their packages

tap homebrew/core
brew gdbm
brew ghq
brew git
brew libevent
brew libyaml
brew lua
brew mas
brew openssl
brew pcre2
brew peco
brew perl
brew pkg-config
brew python
brew readline
brew reattach-to-user-namespace
brew ruby
brew sqlite
brew tmux
brew vim

tap caskroom/cask
cask karabiner-elements
cask dropbox
cask google-chrome
cask java

tap caskroom/versions

tap argon/mas

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 408981434 iMovie (10.1.7)
appstore 409183694 Keynote (7.3)
appstore 409203825 Numbers (4.3)
appstore 409201541 Pages (6.3)
appstore 497799835 Xcode (9.0.1)
