
# tap repositories and their packages

tap argon/mas
brew mas

tap caskroom/cask
cask atom
cask dropbox
cask edgeview
cask google-chrome
cask java
cask slack
cask sourcetree

tap homebrew/core
brew doxygen
brew git
brew libevent
brew lua
brew openssl
brew pkg-config
brew tmux
brew vim --with-lua
brew reattach-to-user-namespace

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 406056744 Evernote (6.10)
appstore 409183694 Keynote (7.0.5)
appstore 409203825 Numbers (4.0.5)
appstore 409201541 Pages (6.0.5)
appstore 497799835 Xcode (8.2.1)
appstore 408981434 iMovie (10.1.4)
