
# tap repositories and their packages

tap argon/mas
brew mas

tap caskroom/cask
cask atom
cask dropbox
cask edgeview
cask google-chrome
cask java
cask netbeans
cask slack
cask sourcetree

tap homebrew/boneyard

tap homebrew/core
brew autoconf
brew doxygen
brew eigen
brew gdbm
brew git
brew gmp
brew ilmbase
brew jpeg
brew libevent
brew libpng
brew libtiff
brew libyaml
brew lua
brew openexr
brew openssl
brew pkg-config
brew pyenv
brew pyenv-virtualenv
brew python3
brew rbenv
brew readline
brew ruby
brew ruby-build
brew sqlite
brew tmux
brew vim --with-lua --with-python3
brew xz

tap homebrew/science
brew opencv3

tap homebrew/versions

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew homebrew/python/numpy

# App Store applications
appstore 406056744 Evernote
appstore 409183694 Keynote
appstore 409203825 Numbers
appstore 409201541 Pages
appstore 497799835 Xcode
appstore 408981434 iMovie
