[tools]
awscli = { version = "latest", symlink_bins = "true" }
bat = "0.26.1"
cargo-binstall = "latest"
"cargo:tree-sitter-cli" = "latest"                     # for neovim
delta = "0.19.1"
eza = "0.23.4"
fd = "10.4.2"
fzf = "0.70.0"
gh = "2.88.1"
"github:vifm/vifm" = "v0.14.3"
go = "1"
jq = "1.8.1"
lazygit = "v0.60.0"
lua = "5.1"                                            # neovim luarocksで要求しているバージョンが5.1
node = "22"
"npm:@aikidosec/safe-chain" = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:mcp-remote" = "latest"                            # for copilot
"npm:neovim" = "latest"                                # for neovim
"pipx:awslabs.aws-documentation-mcp-server" = "latest"
"pipx:oraios/serena" = "latest"                        # for copilot
"pipx:pynvim" = "latest"                               # for neovim
pnpm = "latest"
python = "3.13"
ripgrep = "15.1.0"
rust = "stable"
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
yq = "4.52.5"

[env]
# UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }

[settings]
activate_aggressive = true
experimental = true

[settings.npm]
package_manager = "pnpm"

[settings.pipx]
uvx = true
