[tools]
aws-vault = "7.2.0"
awscli = { version = "2.35.4", symlink_bins = "true" }
cargo-binstall = "1.20.0"
"cargo:tree-sitter-cli" = "0.26.8"                        # for neovim
claude = "2.1.168"
delta = "0.19.2"
fzf = "0.73.1"
gemini-cli = "0.46.0"
gh = "2.94.0"
"github:vifm/vifm" = "v0.14.4"
go = "1.26.4"
jq = "1.8.1"
lazygit = "0.62.2"
lua = "5.1.5"                                             # neovim luarocksで要求しているバージョンが5.1
node = "24.16.0"
neovim = "0.12.2"
opencode = "v1.17.4"
"npm:@aikidosec/safe-chain" = "1.5.7"
"npm:@anthropic-ai/sandbox-runtime" = "0.0.54"
"npm:ccstatusline" = "2.2.19"                             # for claude code
"npm:ccusage" = "20.0.6"                                  # for claude code
"npm:@github/copilot" = "1.0.60"
"npm:context-mode" = "1.0.162"                            # for opencode
"npm:mcp-remote" = "0.1.38"                               # for copilot
"npm:neovim" = "5.4.0"                                    # for neovim
"pipx:awslabs.aws-documentation-mcp-server" = "1.1.24"
"pipx:markitdown-mcp" = { version = "0.0.1a4", all = "" } # for copilot
"pipx:pynvim" = "0.6.0"                                   # for neovim
pnpm = "11.6.0"
python = "3.14.5"
rust = "1.96.0"
shellcheck = "0.11.0"
shfmt = "3.13.1"
ripgrep = "15.1.0"
uv = "0.11.19"
yq = "4.53.3"

# pnpm で post install script の実行などを停止しているので binary 作成を手動で実行
"npm:@tobilu/qmd" = { version = "2.5.3", postinstall = """
  local sqlite3_dir
  sqlite3_dir=$(find "$MISE_TOOL_INSTALL_PATH" -name "binding.gyp" -path "*/better-sqlite3/*" 2>/dev/null | head -1 | xargs -- dirname 2>/dev/null || true)

  if [[ -z "$sqlite3_dir" ]]; then
    echo "better-sqlite3 not found under $mise_installs_dir"
    return 1
  fi

  # ネイティブバイナリが既にビルド済みの場合はスキップ
  if [[ -d "$sqlite3_dir/build" ]]; then
    echo "better-sqlite3 native binding already exists, skipping rebuild"
    return 0
  fi

  echo "Rebuilding better-sqlite3 native binding in $sqlite3_dir ..."
  (cd "$sqlite3_dir" && npx install) || {
    echo "prebuild-install failed"
    return 1
  }
""" }

[env]
ASDF_LUA_LUAROCKS_VERSION = "3.12.2" # 3.13.0 has corrupted rockspec (luarocks/luarocks#1851)
# QMD が aarch64 linux 環境で gpu なしのため強制的に cpu 動作とする(不要にビルドが走ったりするため)
QMD_LLAMA_GPU = "false"
# UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }

[settings]
activate_aggressive = true
experimental = true

[settings.npm]
package_manager = "pnpm"

[settings.pipx]
uvx = true
